### PR TITLE
Punctuation fixes, round two

### PR DESCRIPTION
**Pull request by WoefulWombat**
The rest of the dialogue punctuation, plus a couple other mistakes I noticed, and minus everything that's in /res/txt/. Editing .xml files in eclipse seem tedious and I need some sleep, so I'll look at that tomorrow or whenever I can.

I'm pretty sure I missed a bunch, and there's the usual debatable/preferential stuff, but that can all be ironed out.

### CODE REVIEW

**Comment by WoefulWombat** [comment]
Resolved 0.2.3.5 conflicts.

**Comment by WoefulWombat** [comment]
Resolved 0.2.4 conflicts, fixed mistake on my part.

**Comment by WoefulWombat** [comment]
Resolved 0.2.4.5 conflicts; fixed a few commas I missed.

**Comment by Innoxia** [comment]
Thank you so much for taking the time to do all this! Really, this is a huge, huge help. <3

**Pull request merged**
