### PR TITLE
Tail actions

### PR DESCRIPTION
**Pull request by A-Master-of-Puppets**
I've added the tail actions to all the positions that didn't have them, but individually this time. I have a hard time imagining a position that could preclude tail actions and still be described as "sex", but I suppose it could happen.

### CODE REVIEW

**Comment by WoefulWombat** [comment]
I suppose it depends entirely on the length of the tail and/or your imagination and how much control you have over it. That's something that can certainly be expanded upon in the future—tail length, thickness, and modifiers. 
For instance, IRL cats don't have that much control over their tails, they are not "prehensile" by definition as they can't grasp with it. Very few animals can. So being able to fuck someone with a tail like that makes little sense. unless you say that catgirls do have that extra control and add a "prehensile"-modifier to it.
And then what about shorter tails? Anything below torso length is going to be awkward in 20-30% of all positions.

**Comment by A-Master-of-Puppets** [comment]
Well, tail-fucking is already a thing in the game; it's not something new I'm adding. All I'm doing is enabling the actions for the positions that didn't have them available.

**Comment by WoefulWombat** [comment]
Yeah, I know, I was just rambling about it in general. Should've just written that as a suggestion.

**Comment by Innoxia** [comment]
I've completely changed how the game's sex positions get appropriate sex actions, so this PR is no longer valid. ^^

Thank you very much for your effort though; I did consult this when changing the sex position code. :3

**Pull request closed without merging**
