### PR TITLE
Add new catmorph sub-species

### PR DESCRIPTION
**Pull request by Irbynx**
This commit adds some cat morph sub-species and as a side-effect also makes the game track hair type and face type transformation types automatically like it does with horns, ears and tails.

All subspecies are variants of Cat Morph. I tried to keep the species away from requiring specific color palettes as there is a non-zero amount of furries that love unnatural colors (I mean, sparkledogs exist), so I figured that the colors can be kept freeform for them.

Added parts:
- CAT_EAR_TUFTED; tufted feline ear, like on lynxes or ocelots.
- CAT_TAIL_TUFTED; lion's tufted tail
- CAT_TAIL_SHORT; stubby cat tail
- CAT_FACE_PANTHER; panthera genus' defining face (leopards, lions, tigers, basically all big cats)
- CAT_HAIR_SIDEFLUFF; side fluff for lynxes.

Added sub-species:
- Lynx Morphs: Require character to have side-fluff hair type, tufted ears and short tail.
- Leopard Morphs: Require character to have normal tail, panthera face and short, spotted fur.
- Snow Leopard Morphs: Same as above, but fur should be fluffy (due to that, slimes can't detect them and will just put them as normal leopards)
- Lion Morphs: Short fur, tufted tail, panthera face.
- Tiger Morphs: Striped fur, normal tail, panthera face.
- Cheetahs: Spotted short fur and not detected as any other sub-species. Slimes drop the requirement to simply spotted fur.
- Ocelots: Tufted ears and not detected as any other sub-species.

### CODE REVIEW

**Comment by A-Master-of-Puppets** [comment]
I've been looking forward to big cats, so this is very welcome to me. One issue though; the new face and hair TFs just show as "Cat-morph hair transformation" when enchanting potions. It's a simple enough fix, you just need to add cases for them in the ItemEffectType.getRacialEffect method like there are for ears and tails.

**Comment by Innoxia** [comment]
I will definitely merge this soon! There are some conflicts at the moment that need to be resolved first though. ^^

**Comment by A-Master-of-Puppets** [comment]
Just an issue I've come across; the new cheetah subspecies calls Breast.setSize with a null for the owner parameter, which is not supported currently like setting face or tail types is. I'll throw a PR for that out soon.

**Comment by Irbynx** [comment]
Odd, I thought I've changed the 'null' setter, but maybe I only did it to face and hair and not breast size

**Comment by Rfpnj** [comment]
@Irbynx Any chance of you going back and looking at these conflicts.

**Comment by Irbynx** [comment]
I'll see what I can do about it in a couple of days, hopefully tomorrow.

**Comment by Innoxia** [comment]
I'm merging this into my local code, so this will be added for 0.2.8. Thank you so much for all this! :3

**Pull request merged**
