### PR TITLE
Add missing verb for #1291

### PR DESCRIPTION
**Pull request by TadUnlikely**
- What is the purpose of the pull request?
Fix missing verb for issue #1291 

- Give a brief description of what you changed or added.
A word

- Are any new graphical assets required?
No

- Has this change been tested? If so, mention the version number that the test was based on.
No testing needed, text-only change

### CODE REVIEW

**Comment by TadUnlikely** [comment]
Rebased on top of the dev branch, good to merge, still an issue.

**Comment by AceXP** [comment]
Since the same typo appears in many more xml files, it might be useful to fix all of them.

**Comment by TadUnlikely** [comment]
Fixed in all the files now on my branch. I believe those were new files since I wrote the original, but either way, good catch @AceXP !

**Review by CognitiveMist — APPROVED** [review]

**Comment by Innoxia** [comment]
Thank you for this!

**Pull request merged**
