### PR TITLE
More detailed error messages during mod loading

### PR DESCRIPTION
**Pull request by CognitiveMist**
There are a number of errors that can occur when importing a mod file
which give little idea as to what actually went wrong. This change
adds the filename to importing AbstractClothingType, AbstractTattooType,
and AbstractWeaponType, and adds the exception message to each error
case. Hopefully this will help mod authors figure out what exactly the
problem is.

### Things to include in a large Pull Request:

- What is the purpose of the pull request?
More detailed error reporting when loading mod files

- Give a brief description of what you changed or added.
Added detail to error messages; filename and exception message

- Are any new graphical assets required?
No

- Has this change been tested? If so, mention the version number that the test was based on.
Yes, v0.2.10.8

- So we have a better idea of who you are, what is your Discord Handle?
CognitiveMist|Phlarx

- If you want quick feedback, you can use @Innoxia, or jump on the Lilith's Throne discord and send Innoxia a PM.

### CODE REVIEW

**Comment by Innoxia** [comment]
I'll sort out these merge conflicts first thing when I get up tomorrow. Thank you for this PR. ^^

**Comment by CognitiveMist** [comment]
If you merge #969 (which I'd recommend), then you can close this. I'm just keeping this open till then.

**Comment by CognitiveMist** [comment]
Hmm, the conflicts seem to be due to merging #657. The code structure is much cleaner, but I'm not yet sure how that will impact error messages. I don't know if I'll be available when you get to this (tomorrow is Thanksgiving), but I think either myself and/or Pimvgd (who authored #969) could take a look first, if you like.

**Comment by Pimvgd** [comment]
@CognitiveMist do we need to? #969 has no merge conflicts, and I cherry picked your commit into that one.

**Comment by CognitiveMist** [comment]
@Pimvgd note that Inno changed the base branch of this one to dev, instead of master. The base of #969 is still on master.

**Comment by Innoxia** [comment]
I've merged #969 and credited both you and Pimgd. Thank you for this! ^^

**Pull request closed without merging**
