### PR TITLE
Revaluation of enchantments

### PR DESCRIPTION
**Pull request by Maxis010**
### Things to include in a large Pull Request: ###

- What is the purpose of the pull request?
Balance the value modifiers for items, clothing and weapons

- Give a brief description of what you changed or added.
Changed `getValue()` of AbstractItem, AbstractClothing & AbstractWeapon
Removed any unique valuations

- Are any new graphical assets required?
No

- Has this change been tested? If so, mention the version number that the test was based on.
0.4.5

- So we have a better idea of who you are, what is your Discord Handle?
Maxis010#3060

- If you want quick feedback, you can use @Innoxia, or jump on the Lilith's Throne discord and send Innoxia a PM.

### CODE REVIEW

**Comment by Phlarx** [comment]
If I'm reading this correctly, an shirt with 50 "+1 physique" enchants will be worth *less* than a shirt with a single "+3 physique" enchant. Is that accurate?

**Comment by Maxis010** [comment]
> If I'm reading this correctly, an shirt with 50 "+1 physique" enchants will be worth _less_ than a shirt with a single "+3 physique" enchant. Is that accurate?

Yes, rather than increasing the value for every enchantment it just takes the strongest enchantment as a multiplier

**Comment by CognitiveMist** [comment]
> > If I'm reading this correctly, an shirt with 50 "+1 physique" enchants will be worth _less_ than a shirt with a single "+3 physique" enchant. Is that accurate?
> 
> Yes, rather than increasing the value for every enchantment it just takes the strongest enchantment as a multiplier

Hm, ok. Doesn't make much sense to me, but as long as it's known.

**Comment by Maxis010** [comment]
Considering changing this to factor in number of enchants but at a lesser rate

**Comment by Maxis010** [comment]
> If I'm reading this correctly, an shirt with 50 "+1 physique" enchants will be worth _less_ than a shirt with a single "+3 physique" enchant. Is that accurate?

This is no longer the case, buffed all of the existing modifiers and restored a number of enchants bonus

**Comment by Innoxia** [comment]
Thank you for this! ⚔️✨⚖️✨👗

**Pull request merged**
