### PR TITLE
Item handling rework

### PR DESCRIPTION
**Pull request by KamiKoroshi**
### Things to include in a large Pull Request:

- What is the purpose of the pull request?
This rework should make it easier to read files that are being read from the res folder.

- Give a brief description of what you changed or added.
* Removed a lot of unnecessary code according to the DRY principle.
* Added a Resource and ResourceReader class:
   ResourceReader reads from all the files in res and creates a Resource if it is deemed a Resource.

- Are any new graphical assets required?
No

- Has this change been tested? If so, mention the version number that the test was based on.
Yes
Version 0.3.0

- So we have a better idea of who you are, what is your Discord Handle?
ƘȂMƗǨǾȒǬŜĦĬ#2222

- If you want quick feedback, you can use @Innoxia, or jump on the Lilith's Throne discord and send Innoxia a PM.

### CODE REVIEW

**Comment by KamiKoroshi** [comment]
After testing a bit more, it seems to be unstable right now and suddenly broke.

**Comment by GeneralPikaru** [comment]
I skimmed over the changes to get an idea on what you are trying to accomplish.
Since this is effectively a big refactor, it would be nice if you could jeep track of what exactly you changed, and why and how. This way, especially when someone else reviews this pull (say, AlacoGit, Innoxia or Irbynx) They dont have to figure out whether this actually makes sense, since anyone can contribute. As you yourself stated later, "it seems to be unstable and suddenly broke."
In order to work together on this, we need you to provide the necessary information on your pull (that is a log of additions, changes and deletions) and commentary on why that is necessary. this may also help yourself in dealing with those unforeseen issues you identified yourself.

**Comment by KamiKoroshi** [comment]
> 
> 
> I skimmed over the changes to get an idea on what you are trying to accomplish.
> Since this is effectively a big refactor, it would be nice if you could jeep track of what exactly you changed, and why and how. This way, especially when someone else reviews this pull (say, AlacoGit, Innoxia or Irbynx) They dont have to figure out whether this actually makes sense, since anyone can contribute. As you yourself stated later, "it seems to be unstable and suddenly broke."
> In order to work together on this, we need you to provide the necessary information on your pull (that is a log of additions, changes and deletions) and commentary on why that is necessary. this may also help yourself in dealing with those unforeseen issues you identified yourself.

Will do when I get the time.

Also, this doesn't work as effective as I want to to, because the mods and items have different structures, but that doesn't matter that much.

**Comment by KamiKoroshi** [comment]
I do not have the time for this currently, so I am closing this.
Was fun to fool around trying to get this to work, but don't have the time to figure it out.

**Comment by Innoxia** [comment]
Sorry that I wasn't able to take a look at this and get it merged in time. Thank you for your effort anyway!

**Pull request closed without merging**
