### PR TITLE
Feature/java 17 + visual fixes + release pipeline

### PR DESCRIPTION
**Pull request by Tazze**
<b>Please only submit Pull Requests to the dev branch!</b>

### Things to include in a large Pull Request: ###

- What is the purpose of the pull request?
Make LT runnable directly on the most recent Java LTS (17) and create an automatic build and release pipeline to reduce workload.

- Give a brief description of what you changed or added.
  - Added dependencies for Nashorn and JafaFX which are no longer part of the JDK
  - Added a launcher since non modular (non-jlink) builds can no longer run JavaFX Applications directly
  - Made it so that the WINDOW_IMAGE is not set before JavaFX initializes itself, which causes an exception
  - Use Maven Shade plugin to build the runnable jar
  - Fixed elements that are supposed to be transparent being opaque (for example: disabled buttons)
  - Add a pipeline to compile the game for all the different platforms and architectures as a sanity check
  - Add a pipeline to create a release automatically every time a new tag is pushed

- Are any new graphical assets required?
No.

- Has this change been tested? If so, mention the version number that the test was based on.
Not fully tested on version 0.4.4.5 (game runs, able to start a new game, create a new character and skip the prologue without issues)

- So we have a better idea of who you are, what is your Discord Handle?
Tazze#9319

- If you want quick feedback, you can use @Innoxia, or jump on the Lilith's Throne discord and send Innoxia a PM.

NOTES:
I have decided to add "(WIP)" until I'm sure there are no regressions associated with these changes
How to build and run (linux):
`mvn clean package`
`cd target/Lilith's Throne (linux)`
`java -jar "Lilith's Throne-0.4.6.jar" `

How to build and run (windows)
`mvn clean package -Dtarget.platform=win -Dexclude.platform=linux`
`cd .\target\Lilith's Throne (win)`
`java -jar "Lilith's Throne-0.4.6.jar"` (alternatively, double click the jar file)

### CODE REVIEW

**Comment by ElAcechador** [comment]
See #1588, which is very similar but builds separate builds per platform, among other things.

IIRC this has languished because Innoxia doesn't actually use Maven (I might be wrong, someone please confirm), so it wouldn't be useful to generate the actual builds, but you seem to be using github CI, so that might actually be different.

**Comment by Tazze** [comment]
> See #1588, which is very similar but builds separate builds per platform, among other things.
> 
> IIRC this has languished because Innoxia doesn't actually use Maven (I might be wrong, someone please confirm), so it wouldn't be useful to generate the actual builds, but you seem to be using github CI, so that might actually be different.

My release pipeline is designed to build jars per platform and architecture (for Apple Silicon Macs, x86 Windows and ARM64 Linux, on top of AMD64 builds for all three), see https://github.com/Tazze/liliths-throne-public/releases/tag/v0.4.4.5-hotfix-2 (since you seem to imply my PR doesn't)
I also don't see why maven wouldn't be useful, the jars generated work just fine and are what I use to play the game, since I refuse to install an ancient JDK like 8

This PR also fixes a bunch of visual bugs that occur on current versions of JavaFX because of a slight change in CSS rendering behavior

**Comment by zqqui** [comment]
this update needs to be merged. jdk8 is decrepit

**Comment by Innoxia** [comment]
Thank you for this!

**Pull request merged**
