### PR TITLE
add recorder, recording items.

### PR DESCRIPTION
**Pull request by picobyte**
To add recorder and recording. Spectators that have a recorder, can make a recording of you during a sex scene. Intent is to enable some blackmailing and dialogue as a consequence.

This is just a start and may require some changes before it is functional.

### CODE REVIEW

**Comment by Rfpnj** [comment]
Needs an SVG for each item, but intriguing idea

**Comment by picobyte** [comment]
Both are adapted from copyleft wikimedia commons material. I also have a camera, but it's hard to find a suitable image of a picture and there's no framework for this yet.

**Comment by CognitiveMist** [comment]
@picobyte 

This PR is out of date with some of the code it is based upon. Do you still believe it is useful? Do you think it might be worth updating?

**Comment by Innoxia** [comment]
I'm sorry that I never got around to merging this. If you'd like to fix the merge conflicts and have me re-open this, then please don't hesitate to message me!

**Pull request closed without merging**
