### PR TITLE
TestNG integration

### PR DESCRIPTION
**Pull request by Zsar**
### - What is the purpose of the pull request?
set up automatic test framework

### - Give a brief description of what you changed or added.
1. Maven plugins for automatic tests
2. TestNG, Mockito, AssertJ frameworks for boilerplate test code
3. StringUtils library for boilerplate string manipulation
4. Maven license plugin for automatic license report of dependencies
5. changed project structure to accommodate Maven test goals
6. barebones documentation and example

### - Are any new graphical assets required?
no

### - Has this change been tested? If so, mention the version number that the test was based on.
on "0.3.2.2 Alpha" intensive Maven goal testing, no game executable testing

### - So we have a better idea of who you are, what is your Discord Handle?
Zsar#7336

### CODE REVIEW

**Comment by Innoxia** [comment]
Sorry, but this makes too many changes for something I don't use. I'm not willing to make such drastic changes to folder structure for the sake of maven, as I have no current intention of using it.

**Comment by Zsar** [comment]
Err... if you do not use Maven, why do you use Maven?
I could have set this up without Maven just fine, but Maven is the build chain in use, so I set it up in Maven.

... Meh, I'll redo it.

**Comment by Stadler76** [comment]
Is it really required to move the `src` folder?

**Comment by CognitiveMist** [comment]
@Zsar Innoxia does not use Maven, it was added to the repository by other contributors in an attempt to make it easier for people to make their own builds with little-to-no java experience. While I don't fully understand their reasoning, it seemed useful for some people here and there, so it stayed.

**Pull request closed without merging**
