### PR TITLE
Milk Tax

### PR DESCRIPTION
**Pull request by Maxis010**
### Things to include in a large Pull Request: ###

- What is the purpose of the pull request?
Balance the milking room against the other jobs and fix a dupe bug

- Give a brief description of what you changed or added.
Reduced fluid values and increased upkeep

- Are any new graphical assets required?
No

- Has this change been tested? If so, mention the version number that the test was based on.
0.4.2.4

- So we have a better idea of who you are, what is your Discord Handle?
Maxis010#3060

- If you want quick feedback, you can use @Innoxia, or jump on the Lilith's Throne discord and send Innoxia a PM.

### CODE REVIEW

**Comment by CognitiveMist** [comment]
There is a restriction that the player may only build one spa; would it be worthwhile to restrict the number of milking parlors the player can build? To 4, for example.

(I don't know how many milk rooms are used for a max-capacity milk farm currently.)

I feel like selling all fluids for the same amount is rather bland (even though I usually deal with 'normal' attributes/flavors, myself). Perhaps leave the flavor adjustment in, but take the texture stuff out. Or give a flat boost for non-standard flavor, and another for non-standard texture. Of course, the boost can be much smaller than the existing 50%.

Another idea I had (this would probably fit better into an economy-based nerf, though -- meaning market saturation, etc. -- and also probably require a nontrivial amount of writing):
Change the texture/flavor boosts over time. On one week, honey flavor might have a 20% boost, and the next 0% (meaning it's irrelevant), and the next week it might actually have a 20% penalty. Allow the player to read the market (maybe with upkeep just for being able to do that). This way, a max-efficiency farm needs a lot of player intervention to run at peak profit. If left unmanaged, the profits would be roughly in line with having fully-standard fluids. Of course, the static adjustments in this PR would still be beneficial.

**Comment by defsil** [comment]
> (I don't know how many milk rooms are used for a max-capacity milk farm currently.)

_One slave is all it takes_.

image

And this, of course, is not _nearly_ the max capacity, nor the maximum possible milking profit per slave. It's just that broken. Having to build and fully populate many milking rooms to turn such a profit, on the other hand, would be exactly the intended solution and a great way to earn flames, so there's no point in limiting _that_.

Also, please have a look at [this issue](https://github.com/Innoxia/liliths-throne-public/issues/1538) and the discussion of milking in the comments. :3

**Comment by defsil** [comment]
I must say that, as much as I like the idea of rebalancing milking, perhaps lowering the affection values for it and completely removing flavor & texture influence on the cost is just a bit too much? 
Also, "Increased affection penalty for overworking" should definitely get split into a separate pull. :&)

**Comment by Maxis010** [comment]
> I must say that, as much as I like the idea of rebalancing milking, perhaps lowering the affection values for it and completely removing flavor & texture influence on the cost is just a bit too much?

I'm not lowering the affection of milking, I'm lowering the bonus from the fetishes as with 24 hour milking you can go from -100 to 100 in 4 days, the standard affection rate has not been changed

Modifiers as written was broken, you just add all the modifiers to min/max the price. Without factoring in modifiers regardless of what race goes in the outcome is the same. Flavour could be restored with minimal impact, I removed all modifiers for testing and personally see no reason it needs to be readded.

> Also, "Increased affection penalty for overworking" should definitely get split into a separate pull. :&)
Affection penalties are a part of this rebalancing as there is no real penalty for overworking, even if the min/maxers won't care.
If anything from this PR should be split it's the bug fix I've bundled inside
That said Inno will go over this code with a fine tooth comb and if she has an issue I can easily split the 3 parts of this PR for her.

> There is a restriction that the player may only build one spa; would it be worthwhile to restrict the number of milking parlors the player can build? To 4, for example.
> 
> (I don't know how many milk rooms are used for a max-capacity milk farm currently.)

As defsil has said, 1/8th of a room is all it takes
 
> I feel like selling all fluids for the same amount is rather bland (even though I usually deal with 'normal' attributes/flavors, myself). Perhaps leave the flavor adjustment in, but take the texture stuff out. Or give a flat boost for non-standard flavor, and another for non-standard texture. Of course, the boost can be much smaller than the existing 50%.

I removed all of the modifiers for testing purposes, there is no reason that the 50% flavour boost shouldn't be put back, but I will leave that to Inno to decide

> Another idea I had (this would probably fit better into an economy-based nerf, though -- meaning market saturation, etc. -- and also probably require a nontrivial amount of writing): Change the texture/flavor boosts over time. On one week, honey flavor might have a 20% boost, and the next 0% (meaning it's irrelevant), and the next week it might actually have a 20% penalty. Allow the player to read the market (maybe with upkeep just for being able to do that). This way, a max-efficiency farm needs a lot of player intervention to run at peak profit. If left unmanaged, the profits would be roughly in line with having fully-standard fluids. Of course, the static adjustments in this PR would still be beneficial.

Great idea, but my goal was to counter the 1 million flame/day slaves not build a market sudo-simulation

**Comment by CognitiveMist** [comment]
> One slave is all it takes.

> As defsil has said, 1/8th of a room is all it takes

I fail to see how this is relevant to the suggestion of limiting the number of milking rooms. Of course it won't fix the problem on it's own, nobody suggested that.

Two slaves is always gonna be twice as profitable as one; 64 slaves twice as profitable as 32. If someone had a single full room, and their profits got cut to 10%, they can just build and fill 9 more rooms to get the same profit. A bit more effort? Yes. Same absurd profits? Also yes.

I know I'm drastically oversimplifying, but I'm trying to point out that limiting the number of rooms is also an effective way of limiting profit. Especially since buying/building additional property is still on the cards for future updates.

**Comment by Innoxia** [comment]
Thank you for this!

**Pull request merged**
