### PR TITLE
Slavery Sorting and Book-Keeping

### PR DESCRIPTION
**Pull request by ScottGriffin213**
## Purpose

Adds some QoL stuff for slave management.

Screenshot_20220412_135137
Screenshot_20220412_135345

## Changes

* Added sorting options to the slave list.
* Added some optional text fields to an individual slave's job page for adding notes and a sorting category.
* TextAreas are now styled correctly.

## Graphical Asset Needs

No new graphical assets are required.

## Testing

Tested locally against 0.4.3.9 (commit 944875a52e78f941a402483c88f30fa4bd818bc1). Notes persisted in saves, as well.

## Contact

I am available in the developer Discord as Anonymous-BCFED#8233.

### CODE REVIEW

**Comment by ScottGriffin213** [comment]
I noticed that one of the buttons is broken on 0.4.4.  I'll fix it when I can.

**Comment by ScottGriffin213** [comment]
Okay, ready to go.

**Comment by Innoxia** [comment]
There appear to be formatting issues with the button names and text area, as well as unresponsive tooltips in the text area. I'll try to fix it and get it merged soon.

**Comment by ScottGriffin213** [comment]
Sorry about that.  My primary development machine for adult projects is running Linux and OpenJFX.  That's probably why it looks fine for me but not for you.

**Comment by Innoxia** [comment]
Yeah, it's probably a quirk with the version of JavaFX which I'm using. It should be easy to fix on my end with some css edits, and as such I should have this merged by the end of today.

**Comment by Innoxia** [comment]
(I just merged this, but for some reason github isn't detecting it as merged, so I'll manually close the PR instead.)

Thank you for this PR! I had to remove the category and notes additions, however, as they were causing significant UI input lag during testing. As a result, only the sorting part of your PR has made it into the base game, although that in itself is a big improvement, so thank you!

**Pull request closed without merging**
