### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by Sargalis**
- What is the purpose of the pull request?
Improve dialogs and text descriptions. Getting rid of some mistakes.

- Give a brief description of what you changed or added.
Fixed mistakes in some words.

- Are any new graphical assets required?
No.

- Has this change been tested? If so, mention the version number that the test was based on.
No, it hasn't been tested as it's dialog text fixes.

- So we have a better idea of who you are, what is your Discord Handle?
Lis (Argalis#2179 (Discord ID = 276726951434125332))

- If you want quick feedback, you can use '@'Innoxia, or jump on the Lilith's Throne discord and send Innoxia a PM.
I understand.

**PLEASE IGNORE THE FOLLOWING COMMITS:**
- Delete themiscyra.xml
- Update themiscyra.xml
- Bug fix
I don't know how to remove them from PR...

List of found and fixed typos:
- giva (give) 2 (could be urban speech but I don't think it makes sense in context: "I's gonna giva ya cunt", since "giva ya" sounds unpronounceable, besides 2 lines lower its "I's gonna give ya a good poundin'!") `res/txt/places/submission/ratWarrens/core.xml` 
- kindenss (kindness) 1
- tehre's (there's) 1
- Vangar (Vengar) 1
- Vegnar (Vengar) 1
- 'ungy ('ungry) 1
- anytin' (anythin') 1
- abck (back) 3
- VEngar (Vengar) 1
- SIlence (Silence) 1
- ahev (have) 1
- Maraxis (Meraxis) 2
- Aurokaries (Aurokaris) 1
- Taht (that) 1
- shll (shall) 1
- Evlyx's (Evelyx's) 3 
- glirlcum (girlcum) 1
- wtih (with) 1
- Themiscrya (Themiscyra) 2
- competely (completely) 1
- amybe (maybe)1
- aking (asking) 1
- "Wooly Goodness" ("Woolly Goodness") 2
- throbbig (throbbing) 2
- coutner (counter) 1 
- Olix (Oglix) 1
- Golex (Golix) 1
- unblanced (unbalanced) 1
- succubbi (succubi) 1
- foxtaruesses (foxtauresses) 1
- baphoments (baphomets) 1 
- hestiate (hesitate) 1
- concious (conscious) 3
- soemthing (something) 2
- dissapointed (disappointed) 1 
- femininse (feminise) 1
- reahc (reach) 1
- overwhelmes (overwhelms) 3 (3 uses on 31, I think I also made change in dictionary txt, sorry if I'm not supposed to)
- 'ungery ('ungry) 2 (2 usses on 27)
- foul-mouther (foul-mouthed) 1 (1 to 12)
- thraot (throat) 1
- happing (happening) 2
- ominious (ominous) 1
- etherial (ethereal) 3 
- unconcious (unconscious) 1
- claoca (cloaka) 6
- whirrs (whirs) 2
- signifiacnt (significant) 1
- hurrys (hurries) 1

### CODE REVIEW

**Comment by LiSLua** [comment]
Correction: I didn't change the word:
reefunds (refunds) 2
Since I presumed it was a silly speech.

**Comment by Sargalis** [comment]
Also the files I checked: 
`res/weapons/c4mg1rl` 
I was just scrolling down for some time, until decided to go through specific folders

`res/txt/places/fields`
`res/txt/places/global`
`res/txt/places/submission`
Didn't go for dominion

`res/txt/badEnds`

`res/txt/quests.main`

`res/dialog/innoxia/badEnds`

**Comment by Sargalis** [comment]
Added typo fixes for 
`res/txt/places/dominion`

Only searched for basic typos and most likely I missed most of the logical, repetitive and register typos. 

List of found typos:
- instincively (instinctively) 1
- masturate (masturbate) 1
- forcer (forced) 1
- Helana (Helena) 1
- DEsperate (Desperate) 1
- cuogar (cougar) 1
- agasint (against) 3
- labouriously (laboriously) 3 (Only suggesting this because there is both variants used, even though it is 3 to 1)

**Comment by Sargalis** [comment]
Finished finding typos in `/res/text` folder

List of found typos:
- strated (started) 3
- lets lets (lets) 3
- preapring (preparing) 1
- exclain (exclaim) 1

**Comment by Sargalis** [comment]
- WHy (Why) 1
- hole hole (hole) 1
- doens't (doesn't) 4

**Comment by Sargalis** [comment]
- bog-boys (dog-boys) 2
- teh (the) 1
- preganncy (pregnancy) 1 (in comment section, to not encounter it during CTRL+F search next time)
- the please of (the pleasure of) 1

**Comment by Sargalis** [comment]
I messed up with one unnecessary commit (that grew in two more), so I submitted fixed PR.

**Pull request closed without merging**
