### PR TITLE
Fox-morphs and Youko

### PR DESCRIPTION
**Pull request by tukaima**
This adds fox-morph parts, items, as well as subspecies, and rudimentary encyclopedia entries derived from the unused ones currently in Race.java. ~~Currently one subspecies is recognized, fennecs. The magic fox subspecies (currently named "youko" in the text of this PR, because I can. I've made my thoughts on this matter abundantly clear already, though, so I'll leave it at that.) is "implemented", after a fashion; in particular, they do not spawn naturally, and there is absolutely no procedure for a character to be recognized as one. This is just future-proofing, basically.~~ Three subspecies are recognized: fennecs, youkos, and fennec-youkos.

Graphical assets are complete, including: grape wine, chicken pot pie, race icon, combat boost icon, bottled essence icon, and race book icon.

~~Based on the 0.2.3.9 build, but this should be fine for 0.2.4.0.~~

### CODE REVIEW

**Comment by tukaima** [comment]
Updated to 0.2.4.0. Foxes have also been adjusted so they get semi-realistic fur pattern and coloring.

Here's every possibility. Altogether, 20 different combinations. This does not include fennecs, who are still limited to two color combinations.
- Blonde / Ginger + White / Grey (Red fox)
- Blonde / Ginger + Brown / Black (Cross fox)
- Dark Brown
- Dark Brown + Brown
- Brown
- Brown + Tan
- Tan
- Black
- Black + Grey
- White
- Silver / Grey
- Silver / Grey + White

**Comment by ltpatch** [comment]
https://github.com/ltpatch/liliths-throne-public/tree/tukaima-fox is an 0.2.5.1 merge if you're interested

**Comment by tukaima** [comment]
I'll be updating and doing some other changes related to the magic fox subspecies within the coming days. This will, at minimum, include an actual way to recognize them, and they'll appear in all of the same places that succubi would (at a lower probability).

**Comment by tukaima** [comment]
Updated to 2.5.1, and youko can now spawn in the special alleyways where succubi and incubi do.

**Comment by tukaima** [comment]
It has come to my attention that the race entry text for youko is bad. More specifically, it contradicts information I'd already heard, but happened to forget, because I'm an idiot.

Next commit will rectify this.
Youko encounters and changes may also be reverted because they're kinda dogshit.

**Comment by tukaima** [comment]
Something's broke (working on a commit that hasn't been pushed) and nothing I tried has worked.
I'm going to be resetting this branch to newest and then rebuilding from there, and doing a force push once that's done.
If for any reason you need stuff from the older version of the fox branch, contact me.

**Comment by tukaima** [comment]
Something in commit 0b48f19 seems to foul up fox-morphs in general so that they can't spawn.
I'll be testing solutions for this later, but for now, I'm tired as all hell.

**Comment by Innoxia** [comment]
I'm going to merge and fix this locally, so it should all be sorted for tomorrow's release. :3

**Pull request merged**
