### PR TITLE
Fix for broken images on non-windows

### PR DESCRIPTION
**Pull request by A-Master-of-Puppets**
This capitalises the names of the artwork folders, as mentioned in #322.

### CODE REVIEW

**Comment by Innoxia** [comment]
Can this also be fixed by fixing the `Artwork` class's constructor? It was meant to convert the names to lowercase, but I forgot to put `this.name` in the File constructors.

Basically, just by changing `Artwork`'s name argument to be called nameInput, then changing line 86 to:
`this.name = nameInput.toLowerCase();`

https://github.com/Innoxia/liliths-throne-public/blob/master/src/com/lilithsthrone/rendering/Artwork.java

**Comment by A-Master-of-Puppets** [comment]
That might work, but you'd still have to rename the folders for the harpies and Lilaya, since they have uppercase letters in them already. I think having the folders simply share the name of the classes is probably a better solution.

**Comment by A-Master-of-Puppets** [comment]
OK, that definitely _doesn't_ work. The images still don't show up for most characters, and it actually crashes the game when I try to inspect Lilaya.

**Comment by Innoxia** [comment]
Oh yeah, sorry, I didn't think of that! ^^

Thank you for this PR! <3

**Pull request merged**
