### PR TITLE
Slave group management

### PR DESCRIPTION
**Pull request by orth0dox**
### Things to include in a large Pull Request:

**- What is the purpose of the pull request?**
Allows to set slave permissions for multiple slaves instead of clicking all of them separately.

**- Give a brief description of what you changed or added.**
Press permissions button from they Slave List dialogue and you'll get to modify template that is later on applied to chosen slaves. Neither template nor chosen slaves list doesn't save with game save so far (not sure if needed).

**- Are any new graphical assets required?**
No

**- Has this change been tested? If so, mention the version number that the test was based on.**
Briefly tested, appears working.

**- So we have a better idea of who you are, what is your Discord Handle?**
orth0dox

Notes:
While managing Back buttons behavior i noticed that it works suboptimal in master build. Back button after inspect throws you all the way down instead of slave list, when visiting slave trader back button brings you back to slavery overview (though you never entered it beforehand), etc. Since I didn't refactor this behavior, similar problems appear on these new group dialogues as well.

### CODE REVIEW

**Comment by orth0dox** [comment]
If it passes review I gonna add slave jobs bulk management in similar fashion.

**Comment by Innoxia** [comment]
This sounds very useful! Sorry it's taking me a while to review this, I'll get to it as soon as I can! ^^

**Comment by CognitiveMist** [comment]
@orth0dox 

This PR is out of date with most of the code it is based upon. Do you still believe it is useful? Do you think it might be worth updating?

**Comment by Innoxia** [comment]
I'm sorry that I never got around to merging this. If you'd like to fix the merge conflicts and have me re-open this, then please don't hesitate to message me!

**Pull request closed without merging**
