### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DarkTalon25**
<b>Please only submit Pull Requests to the dev branch!</b>

### Things to include in a large Pull Request: ###

- What is the purpose of the pull request?

- Give a brief description of what you changed or added.

- Are any new graphical assets required?

- Has this change been tested? If so, mention the version number that the test was based on.

- So we have a better idea of who you are, what is your Discord Handle?

- If you want quick feedback, you can use @Innoxia, or jump on the Lilith's Throne discord and send Innoxia a PM.

### CODE REVIEW

**Comment by AceXP** [comment]
No offence, but do you have any idea what a PR is supposed to do?

It's fine if you want to customize your own version of the game. But pushing it to the dev branch is something else entirely.

**Comment by Stadler76** [comment]
Looks like another accidental push like in PR #1192. If so, just close it again. If not: See https://github.com/Innoxia/liliths-throne-public/pull/1192#issuecomment-522277058.

**Comment by DarkTalon25** [comment]
> No offence, but do you have any idea what a PR is supposed to do?
> 
> It's fine if you want to customize your own version of the game. But pushing it to the dev branch is something else entirely.

I was trying to merge the update from the base game into my fork. I figured that since I should have no idea what I'm doing, I should leave this as a draft and wait for things like this to show up.

**Comment by AceXP** [comment]
Fair enough. I usually just pull the latest changes from Innoxia:dev into my branch in the development environment? You should be able to do the same if you have set up the project based on github.
To update the fork, create a PR that says merge into DarkTalon25:dev from Innoxia:dev. So, swapped around. You need to 'compare across forks' to be able to make one.

**Comment by CognitiveMist** [comment]
As Ace said, to accomplish your goal, you should be doing this the other way around (note the little arrow in the middle):
image
(use your own fork, obviously, not mine. And click 'compare across forks' if the repository selector disappears.)


However, the 'normal' way to accomplish this is to just use git normally (git command line, git desktop, git tools in your IDE), to make a merge or rebase commit. The GitHub help pages describe the command-line process: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork.

**Pull request closed without merging**
