### PR TITLE
Adding the Mommy's Lil' Toy and Daddy's Lil' Slut Shirts

### PR DESCRIPTION
**Pull request by Basty96**
### Things to include in a large Pull Request:

- What is the purpose of the pull request?
Adding a set of clothing to the game

- Give a brief description of what you changed or added.
4 under-torso items

- Are any new graphical assets required?
[Basty96.zip](https://github.com/Innoxia/liliths-throne-public/files/2922929/Basty96.zip)

- Has this change been tested? If so, mention the version number that the test was based on.
Tested on v0.3.1.1

- So we have a better idea of who you are, what is your Discord Handle?
thebigdaddyking4536

### CODE REVIEW

**Comment by CognitiveMist** [comment]
I don't understand this change. The files changed tab only shows an update to the build tutorial. Why is the clothing set not just published as a mod?

**Comment by IvoryOwl92** [comment]
> I don't understand this change. The files changed tab only shows an update to the build tutorial. Why is the clothing set not just published as a mod?

And why would you deny their donation just because modding exists? Not everyone who plays this game uses Discord or is even aware of the fact it hosts a mod section for LT. There's a certain commodity in having custom content officially in-game versus having to go to a depository somewhere and installing it manually yourself.

The thing with some mods is that if the author drops from the face of the earth you'll end up with a deprecated file the moment the game gets an update, however, once it has been donated to Inno, said ownership automatically passes to her and that assures it's continued support. But really, LT aims to be "open sourced" - you who write fixes should know that by now.

**Comment by CognitiveMist** [comment]
Right, but there is an established route for adding clothing to the game -- and Inno has said that she will ask if she wants a mod (clothing or otherwise) to be included in the game. If there are no mechanical changes, there needn't be a PR. And even if you did create a PR, you should add the clothing directly to that change instead of having a separate download.

**Comment by Basty96** [comment]
First i didn't know Inno would ask you personally to add them
second this is my first time using github i'm sure to make some errors

**Comment by CognitiveMist** [comment]
I mean, nothing's really stopping you from asking Inno. This stuff seems pretty lore-friendly, and the art looks good to me. But I'd recommend pulling the stuff out of the zip and putting it directly in the change if you're going to go that route.

**Pull request merged**
