### PR TITLE
Gender utility methods

### PR DESCRIPTION
**Pull request by A-Master-of-Puppets**
This adds methods for getting the masculine, feminine, and androgynous equivalents for a given gender.
Also adds isAttractedTo functionality to all GameCharacters, and allows checks against abstract genders rather than only other characters.

### CODE REVIEW

**Comment by A-Master-of-Puppets** [comment]
#357 includes these changes, I'm posting them separately in case #357 is too buggy to accept right now.

**Comment by CognitiveMist** [comment]
Instead of rebuilding the maps every time, you should either use a switch, build the maps outside the functions, or what I would do is move the declaration outside the function, and only build the map if it is null:

```java
Map things = null;
public getThing(Object stuff) {
    if(things == null) {
        things = new Map();
        // construct the map here
    }
    return things.get(stuff);
}
```

**Comment by CognitiveMist** [comment]
@A-Master-of-Puppets 

This PR is out of date with the code it is based upon. Do you still believe it is useful? Do you think it might be worth updating?

**Comment by Innoxia** [comment]
I'm sorry that I never got around to merging this. If you'd like to fix the merge conflicts and have me re-open this, then please don't hesitate to message me!

**Pull request closed without merging**
